d<-iris
d<-d[-5]
d.dist=dist(d)
clus<-hclust(d.dist)
plot(clus,main="Complete Linkage")
clusters<-cutree(clus,3)
table(iris$Species,clusters)
clus1<-hclust(d.dist,method="single")
plot(clus1,main="Single Linkage")
clusters1<-cutree(clus1,3)
table(iris$Species,clusters1)
clus2<-hclust(d.dist,method="average")
plot(clus2,main="Average Linkage")
cluster3<-cutree(clus2,3)
table(iris$Species,cluster3)
